In [1]:
#import libraries
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = torch.tensor([2.,3.,4.])

In [3]:
a

tensor([2., 3., 4.])

In [4]:
random_tensor = torch.rand((2,3))
random_tensor

tensor([[0.4652, 0.3535, 0.7314],
        [0.2258, 0.4052, 0.0536]])

In [5]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
ones  = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
range_tensor = torch.arange(2,14)
range_tensor

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [12]:
#reshape the range_tensor
range_tensor = range_tensor.reshape((6,2))

In [13]:
range_tensor.shape

torch.Size([6, 2])

In [11]:
range_tensor

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [15]:
#zeros like and ones like
zero_like = torch.zeros_like(range_tensor)

In [16]:
zero_like

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [17]:
v = torch.rand(4,5)

In [18]:
v

tensor([[0.0451, 0.2048, 0.8667, 0.5812, 0.6910],
        [0.3612, 0.9763, 0.0418, 0.5691, 0.8603],
        [0.7987, 0.0548, 0.7780, 0.3654, 0.4858],
        [0.5711, 0.6631, 0.4761, 0.8697, 0.2229]])

In [26]:
v.max(),v.shape

(tensor(0.9763), torch.Size([4, 5]))

In [28]:
v.argmax(),v.mean()

(tensor(6), tensor(0.5242))

In [29]:
m.sum()

tensor(77)

In [21]:
m = torch.arange(2,13)


In [22]:
m.max()

tensor(12)

In [23]:
m.argmax()

tensor(10)

In [24]:
m.shape

torch.Size([11])

In [25]:
m

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
v.sum()

tensor(10.4832)

In [31]:
v.reshape((5,4))

tensor([[0.0451, 0.2048, 0.8667, 0.5812],
        [0.6910, 0.3612, 0.9763, 0.0418],
        [0.5691, 0.8603, 0.7987, 0.0548],
        [0.7780, 0.3654, 0.4858, 0.5711],
        [0.6631, 0.4761, 0.8697, 0.2229]])

In [33]:
v.shape

torch.Size([4, 5])

In [34]:
t = torch.rand((4,5))

In [35]:
horizontal_stack = torch.stack((t,v),dim = 0)

tensor([[[0.8888, 0.9763, 0.5529, 0.9184, 0.9585],
         [0.3716, 0.0932, 0.2643, 0.3709, 0.9603],
         [0.4651, 0.8119, 0.1276, 0.7376, 0.0859],
         [0.9258, 0.7676, 0.4553, 0.2705, 0.3323]],

        [[0.0451, 0.2048, 0.8667, 0.5812, 0.6910],
         [0.3612, 0.9763, 0.0418, 0.5691, 0.8603],
         [0.7987, 0.0548, 0.7780, 0.3654, 0.4858],
         [0.5711, 0.6631, 0.4761, 0.8697, 0.2229]]])

In [36]:
vertical_stack = torch.stack((t,v),dim = 1)

In [37]:
vertical_stack

tensor([[[0.8888, 0.9763, 0.5529, 0.9184, 0.9585],
         [0.0451, 0.2048, 0.8667, 0.5812, 0.6910]],

        [[0.3716, 0.0932, 0.2643, 0.3709, 0.9603],
         [0.3612, 0.9763, 0.0418, 0.5691, 0.8603]],

        [[0.4651, 0.8119, 0.1276, 0.7376, 0.0859],
         [0.7987, 0.0548, 0.7780, 0.3654, 0.4858]],

        [[0.9258, 0.7676, 0.4553, 0.2705, 0.3323],
         [0.5711, 0.6631, 0.4761, 0.8697, 0.2229]]])

In [38]:
vertical_stack.shape

torch.Size([4, 2, 5])

In [39]:
v_stacked = torch.stack([v,v],dim = 0)

In [40]:
v_stacked

tensor([[[0.0451, 0.2048, 0.8667, 0.5812, 0.6910],
         [0.3612, 0.9763, 0.0418, 0.5691, 0.8603],
         [0.7987, 0.0548, 0.7780, 0.3654, 0.4858],
         [0.5711, 0.6631, 0.4761, 0.8697, 0.2229]],

        [[0.0451, 0.2048, 0.8667, 0.5812, 0.6910],
         [0.3612, 0.9763, 0.0418, 0.5691, 0.8603],
         [0.7987, 0.0548, 0.7780, 0.3654, 0.4858],
         [0.5711, 0.6631, 0.4761, 0.8697, 0.2229]]])

In [41]:
v_stacked.shape

torch.Size([2, 4, 5])

In [42]:
new = torch.rand(2,2)

In [43]:
new

tensor([[0.8373, 0.7317],
        [0.2664, 0.5352]])

In [44]:
new.shape


torch.Size([2, 2])

In [46]:
new_stack = torch.hstack((new,new))

In [47]:
new_stack

tensor([[0.8373, 0.7317, 0.8373, 0.7317],
        [0.2664, 0.5352, 0.2664, 0.5352]])

In [49]:
new_stack_2 = torch.stack([new,new],dim = 1)
new_stack_2,new_stack_2.shape

(tensor([[[0.8373, 0.7317],
          [0.8373, 0.7317]],
 
         [[0.2664, 0.5352],
          [0.2664, 0.5352]]]),
 torch.Size([2, 2, 2]))

In [50]:
new_stack_3 =  torch.stack([new,new],dim = 0)
new_stack_3,new_stack_3.shape

(tensor([[[0.8373, 0.7317],
          [0.2664, 0.5352]],
 
         [[0.8373, 0.7317],
          [0.2664, 0.5352]]]),
 torch.Size([2, 2, 2]))

In [51]:
a  = torch.tensor([2.,4.])

In [52]:
a

tensor([2., 4.])

In [53]:
a = a.numpy()

In [54]:
type(a)

numpy.ndarray

In [55]:
a

array([2., 4.], dtype=float32)

In [56]:
b =  torch.tensor([2.,4.]) 

In [57]:
a = torch.from_numpy(a)

In [58]:
type(a)

torch.Tensor

In [60]:
if torch.cuda.is_available():
    device = 'cuda'
elif torch.backends.mps.is_available():
    device = 'mps'
else:
    device = 'cpu'
    

In [61]:
device

'mps'

In [62]:
n1 = torch.rand((2,3),
                device = device)

In [64]:
n1.device

device(type='mps', index=0)

In [65]:
n1.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [67]:
n1.cpu().numpy()

array([[0.13038027, 0.19225347, 0.84824646],
       [0.721014  , 0.05657113, 0.679373  ]], dtype=float32)

In [71]:
torch.manual_seed(0)
rd_tensor1 = torch.rand((7,7))
rd_tensor2 = torch.rand((1,7))
multi = torch.matmul(rd_tensor1,rd_tensor2.T)

In [72]:
multi

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [73]:
torch.mps.manual_seed(42)